L = {} -- English Content Strings

///////////////////// -- [[ Brute Force ]] --
-- Weapons
ws = "tacrp_m_"
w = ws .. "bamaslama"
L["wep." .. w .. ".name"] = "Alabama Slammer"
L["wep." .. w .. ".desc"] = "A bowie knife named after a cocktail, featuring a serrated back edge and a bayonet mount."
L["wep." .. w .. ".desc.quote"] = "\"Did I say you could do that?\""
L["wep." .. w .. ".credits"] = "Model: Havok101 \nTextures: Millenia"

w = ws .. "bat"
L["wep." .. w .. ".name.full"] = "Loisville Slugger TPX"
L["wep." .. w .. ".name"] = "Slugger"
L["wep." .. w .. ".desc"] = "Aluminum baseball bat, good for hitting home runs or cracking skulls."
L["wep." .. w .. ".desc.quote"] = "\"Pop quiz! How long's it take to beat a moron to death?\""
L["wep." .. w .. ".credits"] = "Model & Textures: Yogensia \nAnimations: Lazarus"

w = ws .. "bayonet"
L["wep." .. w .. ".name"] = "M9 Phrobis III"
L["wep." .. w .. ".desc"] = "Military standard-issue knife that can be mounted on a weapon as a bayonet. Nothing stopping you from using it like a normal knife, however."
L["wep." .. w .. ".desc.quote"] = "Un-fix bayonets! ...wait what?"
L["wep." .. w .. ".credits"] = "Assets: BrainBread 2"

w = ws .. "boina"
L["wep." .. w .. ".name"] = "Cudeman Boina Verde"
L["wep." .. w .. ".desc"] = "Sturdy, oversized survival knife. \n\"Boina verde\" is Spanish for \"green beret,\" an attempt to market the knife as military-grade."
L["wep." .. w .. ".desc.quote"] = "Actually a pretty good knife, despite the false \"military-grade\" claims."
L["wep." .. w .. ".credits"] = "Model & Textures: Shortez"

w = ws .. "cleaver"
L["wep." .. w .. ".name"] = "Meat Cleaver"
L["wep." .. w .. ".desc"] = "Large, sturdy blade made for chopping meat, be that animal meat or human meat. Has innate Lifesteal."
L["wep." .. w .. ".desc.quote"] = "\"A little of the ol' 'chop-chop'!\""
L["wep." .. w .. ".credits"] = "Assets: Warface"

w = ws .. "crowbar"
L["wep." .. w .. ".name"] = "Crowbar"
L["wep." .. w .. ".desc"] = "All-purpose utility tool meant for prying things open; crates, safes, doors and humans!"
L["wep." .. w .. ".desc.quote"] = "\"I think you dropped this back in Black Mesa.\""
L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2"

w = ws .. "css"
L["wep." .. w .. ".name"] = "The Classic"
L["wep." .. w .. ".desc"] = "A classic knife design from the 90's, before fancy patterns and ludicrous prices were all the rage."
L["wep." .. w .. ".desc.quote"] = "\"Alright, let's move out!\""
L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Source"

w = ws .. "fasthawk"
L["wep." .. w .. ".name"] = "SOG Fasthawk"
L["wep." .. w .. ".desc"] = "Modernized tomahawk designed for combat. Aerodynamic design can be thrown far."
L["wep." .. w .. ".desc.quote"] = "Scalper + Bank Shot + First Blood + Longshot"
L["wep." .. w .. ".credits"] = "Model & Textures: Yogensia"

w = ws .. "gerber"
L["wep." .. w .. ".name.full"] = "Gerber LMF Infantry"
L["wep." .. w .. ".name"] = "LMF Infantry"
L["wep." .. w .. ".desc"] = "Compact knife for survival situations, such as gutting fish, carving wood or gutting and carving an enemy."
L["wep." .. w .. ".desc.quote"] = "No, not the same company that makes baby food."
L["wep." .. w .. ".credits"] = "Model: Macaroane \nTextures: Blackfire"

w = ws .. "glock"
L["wep." .. w .. ".name.full"] = "Glock Feldmesser 78"
L["wep." .. w .. ".name"] = "Feldmesser 78"
L["wep." .. w .. ".desc"] = "A sturdy field knife with a firm grip, designed for use within the Austrian Jagdkommando."
L["wep." .. w .. ".desc.quote"] = "Yes, this is the same Glock that makes pistols."
L["wep." .. w .. ".credits"] = "Model: HellSpike \nTextures: Dr. Hubbler"

w = ws .. "hamma"
L["wep." .. w .. ".name"] = "Hammer"
L["wep." .. w .. ".desc"] = "Common craftsman tool for inserting nails into wood or securing objects in place."
L["wep." .. w .. ".desc.quote"] = "When you have a hammer, everything looks like a nail..."
L["wep." .. w .. ".credits"] = "Model: FearFisch & sHiBaN \nTextures: Meltdown, sHiBaN & Kitteh"

w = ws .. "harpoon"
L["wep." .. w .. ".name.full"] = "Extrema Ratio Harpoon"
L["wep." .. w .. ".name"] = "Harpoon"
L["wep." .. w .. ".desc"] = "Thin-bladed knife with serrations on the back edge for extra deep penetration."
L["wep." .. w .. ".desc.quote"] = "Stab, stab, stab, and stab some more!"
L["wep." .. w .. ".credits"] = "Model: Warfrog \nTextures: kannoe"

w = ws .. "heathawk"
L["wep." .. w .. ".name"] = "Heat Hawk"
L["wep." .. w .. ".desc"] = "Axe-shaped MS weapon scaled down to human size.\nThe original utilizes a superheated edge to cut through metal like butter, but this replica only has a glowing decal."
L["wep." .. w .. ".desc.quote"] = "The melee weapon of choice for the MS-06 Zaku II."
L["wep." .. w .. ".credits"] = "Model & Textures: Amouro"

w = ws .. "incorp"
L["wep." .. w .. ".name"] = "Viper Knife"
L["wep." .. w .. ".desc"] = "Flashy flip knife with a premium stainless finish and woodgrain handle."
L["wep." .. w .. ".desc.quote"] = "A quality knife, no doubt."
L["wep." .. w .. ".credits"] = "Model & Textures: Teh Snake"

w = ws .. "kitchen"
L["wep." .. w .. ".name"] = "Kitchen Knife"
L["wep." .. w .. ".desc"] = "Plain, simple kitchen knife. Easy to acquire and adequately lethal, knives like these are popular among street gangs and psychopaths. Has innate Lifesteal."
L["wep." .. w .. ".desc.quote"] = "Oi mate, you gotta license for that knife?"
L["wep." .. w .. ".credits"] = "Model: Kitteh \nTextures: Rochenback"

w = ws .. "knife3"
L["wep." .. w .. ".name"] = "Task Force Knife"
L["wep." .. w .. ".desc"] = "Oversized knife with a serrated edge and a curved handle, a bit overkill for what's supposed to be a military knife."
L["wep." .. w .. ".desc.quote"] = "\"MOM GET THE CAMERA!!\""
L["wep." .. w .. ".credits"] = "Model: Syncing \nTextures: Boba Fett"

w = ws .. "kukri"
L["wep." .. w .. ".name"] = "Kukri"
L["wep." .. w .. ".desc"] = "Short knife with a curved blade, supposedly designed as such so it hooks onto targets and inflicts maximum damage."
L["wep." .. w .. ".desc.quote"] = "\"Professionals have standards.\""
L["wep." .. w .. ".credits"] = "Model: Loyen \nTextures: Pain_Agent"

w = ws .. "machete"
L["wep." .. w .. ".name"] = "Machete"
L["wep." .. w .. ".desc"] = "Versatile blade that can be used as an agricultural tool, a weapon of war or as a navigational aid when deep in the bush."
L["wep." .. w .. ".desc.quote"] = "ki ki ki... ma ma ma..."
L["wep." .. w .. ".credits"] = "Assets: BrainBread 2"

w = ws .. "pan"
L["wep." .. w .. ".name"] = "Frying Pan"
L["wep." .. w .. ".desc"] = "Stovetop cooking device made of solid cast-iron. Made iconic as a weapon through slapstick and cartoons."
L["wep." .. w .. ".desc.quote"] = "CLANG CLANG CLANG CLANG CLANG CLANG CLANG CLANG CLANG CLANG CLANG CLANG"
L["wep." .. w .. ".credits"] = "Assets: Left 4 Dead 2"

w = ws .. "pipe"
L["wep." .. w .. ".name"] = "Lead Pipe"
L["wep." .. w .. ".desc"] = "Sturdy lead water pipe. Despite not being designed for any kind of harm-doing, hitting someone with it does quite a lot of harm."
L["wep." .. w .. ".desc.quote"] = "\"OH SHIT!! Too late!!\""
L["wep." .. w .. ".credits"] = "Assets: No More Room in Hell"

w = ws .. "rambo"
L["wep." .. w .. ".name"] = "Bowie Knife"
L["wep." .. w .. ".desc"] = "A classic fixed-blade knife design made for dueling. \nRemains popular due to its association with overly-masculine 80's action movie stars."
L["wep." .. w .. ".desc.quote"] = "I felt there was something terribly ambiguous about the name."
L["wep." .. w .. ".credits"] = "Model: fallschirmjager \nTextures: HellSpike & EinHain"

w = ws .. "shovel"
L["wep." .. w .. ".name"] = "Shovel"
L["wep." .. w .. ".desc"] = "An old army shovel, designed to quickly dig trenches. Works great as a crude melee weapon, having both a blunt face and a sharp edge."
L["wep." .. w .. ".desc.quote"] = "\"Maggots!\""
L["wep." .. w .. ".credits"] = "Assets: Day of Defeat: Source"

w = ws .. "tonfa"
L["wep." .. w .. ".name"] = "Police Baton"
L["wep." .. w .. ".desc"] = "Specialized police baton with an angled handle for an alternative grip. Useful for putting down riots in failing \"democratic\" nations."
L["wep." .. w .. ".desc.quote"] = "\"You call this resisting arrest?! We call this a difficulty tweak!\""
L["wep." .. w .. ".credits"] = "Assets: Left 4 Dead 2"

w = ws .. "tracker"
L["wep." .. w .. ".name"] = "Tracker Knife"
L["wep." .. w .. ".desc"] = "Oversized gut knife designed for multiple hunting utilities, one of which is, conveniently, slicing open human targets."
L["wep." .. w .. ".desc.quote"] = "I never lose track of what is mine."
L["wep." .. w .. ".credits"] = "Model: Cartman \nTextures: Henron & Fxdarkloki"

w = ws .. "wiimote"
L["wep." .. w .. ".name.full"] = "Nintendo Wii Remote"
L["wep." .. w .. ".name"] = "Wii Remote"
L["wep." .. w .. ".desc"] = "An iconic controller with revolutionary motion controls.\nCareful! Neglecting to wear the wrist strap could lead to injury or property damage."
L["wep." .. w .. ".desc.quote"] = "You're Out!" -- Wii Sports
L["wep." .. w .. ".credits"] = "Model & Textures: Mr. Pickle"

w = ws .. "wrench"
L["wep." .. w .. ".name"] = "Pipe Wrench"
L["wep." .. w .. ".desc"] = "Sturdy wrench designed for tightening water and gas pipes. All-iron construction makes it quite the blunt weapon."
L["wep." .. w .. ".desc.quote"] = "When someone says \"killer service\", they don't mean THIS!"
L["wep." .. w .. ".credits"] = "Assets: Counter-Strike: Online 2"